name: Предложить улучшение
description: Если вы нашли в документе ошибку, неточность или считате что можно что-то дополнить, или что-то устарело или некорректно — предложите исправление.
title: "[Улучшение]: "
labels: [improvement]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо что хотите помочь нам улучшить документацию! Заполните форму ниже для того чтобы создать задачу.
  - type: input
    id: content
    attributes:
      label: Содержимое
      description: URL-адрес материала для которого вы хотите создать обращение.
      placeholder: "Например: https://druki.ru/wiki/drupal, docs/ru/drupal/index.md"
    validations:
      required: true
  - type: textarea
    id: propose
    attributes:
      label: Улучшение
      description: Опишите какие улучшения по вашему мнению должны быть внесены.
      placeholder: Слишком сложно написано, можно написать проще!
    validations:
      required: true
  - type: dropdown
    id: can-do-it
    attributes:
      label: Желаете внести измнения самостоятельно?
      description: Если хотите внести изменения сами, или попробовать это сделать, без проблем! Мы поможем и подскажем как контрибутить. Не хотите? Не проблема, мы можем сделать сами.
      options:
        - Да
        - Нет
    validations:
      required: true
